### ISSUE TITLE
Map from openStreetMap doesn't work

### ISSUE THREAD

**Issue by lilouch** [ros-geographic-info/open_street_map#6] opened 2015-06-04 08:43 UTC
Hi,

I using this package to visualize in Rviz maps. I was able to use it with the pre existed map but It doesn't work when I used a map downloaded from OpenStreetMap.

Can you please help me ?

Thanks you

**Comment by lilouch** [comment] 2015-06-04 08:50
Okey I was able to make it works. I didn't see this issue: https://github.com/ros-geographic-info/open_street_map/issues/5

So I use this tool http://www.rcn.montana.edu/resources/converter.aspx to change

 <node pkg="tf" type="static_transform_publisher" name="local_map_tf" args="622150 3362350 0 0 0 0 1 map local_map 100" />

I replaced the number 622150 and 3362350 with the number provided by the website once I put the longitude and latitude.

**Comment by jack-oquin** [comment] 2015-06-09 21:15
Closing this as a duplicate of #5 

Feel free to submit a pull request, if you have a general fix in mind.

**Closed by jack-oquin** 2015-06-09 21:15 UTC
